### ISSUE TITLE
Correction des imports

### ISSUE THREAD

**Issue by etiennelndr** [CNES/ccsdsmo-malgo#2]
Afin de pouvoir effectuer correctement un **go get** du projet il faudrait que les imports soient modifiés en conséquence. En théorie chaque import d'un package mal devrait commencer par un chemin absolu et non relatif. Par exemple, cela donnerait pour le package mal:
`import "github.com/ccsdsmo/malgo/src/mal"`,
au lieu de:
`import "mal"`

**Comment by freyssin** [comment]
The codebase has been refactored to meet the Go language recommendations.
The project can now be imported by a "go get" command, the import for the mal package is now : 
`import github.com/ccsdsmo/malgo/mal`

**Comment by etiennelndr** [comment]
We still have a little problem. Indeed, you modified the mal path by adding directories and it created new errors. In my opinion, putting the three directories mal, malactor and tests in github.com/ccsdsmo/malgo would be better.
