### ISSUE TITLE
Composite interface is non-exported

### ISSUE THREAD

**Issue by etiennelndr** [CNES/ccsdsmo-malgo#5]
I am currently creating the ArchiveService and I need to create structures that extend the MAL Composite interface. But there is a little problem: I can't create these structures because the `composite()` function begins with a lowercase letter. For the moment, the function is **non-exported** because it is implemented like this:
```
type Composite interface {
	Element
	composite() Composite
}
```
Is it possible to change its implementation like this ? (starting with an **uppercase**)
```
type Composite interface {
	Element
	Composite() Composite
}
```
Thank you in advance.

**Comment by freyssin** [comment]
It's true, may be we have a similar problem with Attribute interface.
